# Generated by Django 3.2 on 2021-04-19 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=40)),
                ('disposition', models.CharField(max_length=30)),
                ('availability', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
